# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5, verbose_name='Logradouro Numero')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Logradouro',
                'ordering': ['cidade'],
                'verbose_name_plural': 'Logradouros',
            },
        ),
    ]
