# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Cidades',
                'ordering': ['cidade'],
                'verbose_name': 'Cidade',
            },
        ),
        migrations.AlterModelOptions(
            name='logradouro',
            options={'ordering': ['logradouro'], 'verbose_name': 'Logradouro', 'verbose_name_plural': 'Logradouros'},
        ),
        migrations.RemoveField(
            model_name='logradouro',
            name='uf',
        ),
        migrations.AlterField(
            model_name='logradouro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='endereco.Cidade', verbose_name='Cidade'),
        ),
    ]
