# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsavel',
            options={'ordering': ['nome'], 'verbose_name': 'Responsavel', 'verbose_name_plural': 'Responsaveis'},
        ),
    ]
