# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEscola', models.CharField(max_length=100, unique=True, verbose_name='Nome Escola')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.Logradouro', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Escola',
                'ordering': ['nomeEscola'],
                'verbose_name_plural': 'Escolas',
            },
        ),
    ]
