# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 15:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='escola',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
