# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_auto_20170525_1238'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='escola',
            managers=[
            ],
        ),
    ]
