# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_auto_20170525_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.Logradouro', verbose_name='Endereço'),
        ),
    ]
