# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0002_auto_20170526_1114'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('numeroDDD', models.CharField(max_length=5, verbose_name='DDD')),
                ('Telefone', models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero Fixo')),
                ('celular', models.CharField(max_length=9, verbose_name='Numero Celular')),
                ('categoria', models.CharField(max_length=2, verbose_name='Categoria Habilitação')),
                ('criadoEm', models.DateField(auto_now=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='endereco.Logradouro', verbose_name='endereco')),
            ],
            options={
                'verbose_name': 'Motorista',
                'ordering': ['nome'],
                'verbose_name_plural': 'Motoristas',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoVeiculo', models.CharField(max_length=100, verbose_name='Tipo Veiculo')),
                ('capacidade', models.PositiveIntegerField(default=50)),
                ('responsavel', models.ManyToManyField(blank=True, null=True, related_name='responsavel', to='cliente.Responsavel', verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'ordering': ['tipoVeiculo'],
                'verbose_name_plural': 'Veiculos',
            },
        ),
        migrations.AddField(
            model_name='motorista',
            name='veiculo',
            field=models.ManyToManyField(related_name='Veiculos', to='motorista.Veiculo', verbose_name='Veiculos'),
        ),
    ]
