# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorista',
            old_name='Telefone',
            new_name='telefone',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='responsavel',
            field=models.ManyToManyField(blank=True, related_name='responsavel', to='cliente.Responsavel', verbose_name='Pais'),
        ),
    ]
