# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0002_auto_20170526_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='apelido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido'),
        ),
    ]
