# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0003_motorista_apelido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='motorista',
            name='veiculo',
            field=models.ForeignKey(default=1618, on_delete=django.db.models.deletion.CASCADE, related_name='Veiculos', to='motorista.Veiculo', verbose_name='Veiculos'),
            preserve_default=False,
        ),
    ]
