# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0004_auto_20170526_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='descricao',
            field=models.TextField(blank=True, default='Venha conecer nossos serviços', null=True, verbose_name='Descrição'),
        ),
    ]
